### YamlMime:PythonClass
uid: azure.mgmt.cosmosdb.models.ConnectionError
name: ConnectionError
fullName: azure.mgmt.cosmosdb.models.ConnectionError
module: azure.mgmt.cosmosdb.models
inheritances:
- msrest.serialization.Model
summary: ConnectionError.
constructor:
  syntax: 'ConnectionError(*, connection_state: typing.Union[str, _ForwardRef(''ConnectionState''),
    NoneType] = None, i_p_from: typing.Union[str, NoneType] = None, i_p_to: typing.Union[str,
    NoneType] = None, port: typing.Union[int, NoneType] = None, exception: typing.Union[str,
    NoneType] = None, **kwargs)'
  parameters:
  - name: connection_state
    description: 'The kind of connection error that occurred. Possible values include:

      "Unknown", "OK", "OperatorToDataCenterNetworkError", "DatacenterToDatacenterNetworkError",

      "InternalOperatorToDataCenterCertificateError", "InternalError".'
    isRequired: true
    types:
    - <xref:str>
    - <xref:azure.mgmt.cosmosdb.models.ConnectionState>
  - name: i_p_from
    description: The IP of host that originated the failed connection.
    isRequired: true
    types:
    - <xref:str>
  - name: i_p_to
    description: The IP that the connection attempted to reach.
    isRequired: true
    types:
    - <xref:str>
  - name: port
    description: The TCP port the connection was attempted on.
    isRequired: true
    types:
    - <xref:int>
  - name: exception
    description: Detailed error message about the failed connection.
    isRequired: true
    types:
    - <xref:str>
